### ISSUE TITLE
Feature request: Smart defaults for text values

### ISSUE THREAD

**Issue by jonom** [Little-Giant/silverstripe-seeder#14]
I gather that if you don't set a specific provider appropriate content is generated based on the field type. That's great but I was wondering if we could take it a step further and look at the name of the field too? This would be really handy for Text and Varchar fields which are used very often but their schema doesn't tell us much useful about the content going in to them.

So if it's 'Title' maybe you get a sentence of 3 - 10 words with no terminating period. For Address and Name we could use the equivalent methods in Faker. If the name ends in 'URL' we could generate a URL. That kind of thing.

**Comment by chrisahhh** [comment]
This is already implemented but probably needs more thought put into it, I know some of the rules aren't matching correctly as well. If you want to have a look at the current rules then check out https://github.com/Little-Giant/silverstripe-seeder/blob/master/_config/heuristic.yml

**Comment by jonom** [comment]
Oh awesome! So just could use some tweaking then. I'll have a little play and open a PR if I come up with some good ones.

**Comment by chrisahhh** [comment]
Yeah most likely needs tweaking, I haven't written any tests as it's not that straight forward to test it. So I can't verify it works reliably

**Comment by jonom** [comment]
Hmm yeah most of the stuff I suggested seems to be already in that heuristics file but I'm not sure that any of it is working for me

**Comment by chrisahhh** [comment]
Yeah there may have been a regression, I'll look into it when I get back from holiday along with the rest of the stuff. Unfortunately I've been really busy since new years. If you'd like it now you can always fork and pull request later!

**Comment by jonom** [comment]
I've been digging around but can't see how to fix it easily, but there's no rush :) enjoy your holiday!
