### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by jonom** [Little-Giant/silverstripe-seeder#6]
I tried taking this module for a spin but the cli just spits out the html for a 'Page not found' response. Any tips on getting past that?

Also the yml code in example uses double dash `--` but that causes a fatal error for me, apparently needs to be triple `---`.

**Comment by stevie-mayhew** [comment]
Hey @jonom 

Looks like this is an issue with 3.2 and this module, I'll get a fix whipped up for you ASAP

**Comment by jonom** [comment]
Thanks man :)

**Comment by stevie-mayhew** [comment]
@jonom dev-master is now 3.2 compatible. We're going to be merging in a few more additions so no tag for right now, should have one later in the day :)

**Comment by jonom** [comment]
That was fast! Working like a charm now, thanks. This module is going to be very useful!

**Comment by stevie-mayhew** [comment]
Nothing like someone else to ask you to do work you've been meaning to do for weeks but don't get around to ;)
